version: "3.7"
services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
    - '27017:27017'
    volumes:
    - ~/apps/mongo:/data/db
    environment:
    - MONGO_INITDB_ROOT_USERNAME
    - MONGO_INITDB_ROOT_PASSWORD